# Deploy to AKP instance: https://stage.akp.foo-org.com
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bar-mfe-frontend-stage
  namespace: argocd
  labels:
    platform.foo-org.com/tenant: "bar"
    platform.foo-org.com/environment: "stage"
    platform.foo-org.com/managed-by: "platform-generator"
    team: "bar"
    business-unit: "sales"
  annotations:
    contact: "Fred Bloggs"
    cost-center: "001"
spec:
  generators:
    - git:
        repoURL: https://dev.azure.com/foo-org/Team-Bar/_git/bar-gitops-config
        revision: HEAD
        files:
          - path: apps/*/config.json
  template:
    metadata:
      name: '{{ cluster }}-{{ app }}'
      labels:
        platform.foo-org.com/tenant: "bar"
        platform.foo-org.com/environment: "stage"
        platform.foo-org.com/managed-by: "platform-generator"
        team: "bar"
        business-unit: "sales"
    spec:
      project: tenant-bar
      source:
        repoURL: https://dev.azure.com/foo-org/Team-Bar/_git/bar-mfe-frontend
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: '{{ server }}'
        namespace: bar-gitops-stage
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=false