apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: bar-gitops-dev
  labels:
    platform.foo-org.com/tenant: "bar"
    platform.foo-org.com/environment: "dev"
    platform.foo-org.com/managed-by: "platform-generator"
    team: "bar"
    business-unit: "sales"
  annotations:
    description: "Allow ingress from monitoring namespace"spec:
  endpointSelector: {}  ingress:
    - fromCIDR:
      toPorts:
      - ports:
        - port: "8080"
          protocol: TCP
