apiVersion: v1
kind: ResourceQuota
metadata:
  name: bar-quota
  namespace: bar-gitops-stage
  labels:
    platform.foo-org.com/tenant: "bar"
    platform.foo-org.com/environment: "stage"
    platform.foo-org.com/managed-by: "platform-generator"
    team: "bar"
    business-unit: "sales"
  annotations:
    contact: "Fred Bloggs"
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "10"
    limits.memory: "20Gi"