apiVersion: v1
kind: Namespace
metadata:
  name: bar-gitops-dev
  labels:
    platform.foo-org.com/tenant: "bar"
    platform.foo-org.com/environment: "dev"
    platform.foo-org.com/managed-by: "platform-generator"
    platform.foo-org.com/cluster: "foo-gitops-wus3-dev"
    team: "bar"
    business-unit: "sales"
  annotations:
    contact: "Fred Bloggs"
