apiVersion: v1
kind: Namespace
metadata:
  name: bar-gitops-stage
  labels:
    platform.foo-org.com/tenant: "bar"
    platform.foo-org.com/environment: "stage"
    platform.foo-org.com/managed-by: "platform-generator"
    platform.foo-org.com/cluster: "foo-gitops-eus-stage"
    team: "bar"
    business-unit: "sales"
  annotations:
    contact: "Fred Bloggs"
