apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: bar-gitops-stage
  labels:
    platform.foo-org.com/tenant: "bar"
    platform.foo-org.com/environment: "stage"
    platform.foo-org.com/managed-by: "platform-generator"
    team: "bar"
    business-unit: "sales"
  annotations:
    description: "Allow pod-to-pod communication within the same namespace"
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
      - {}
  egress:
    - toEndpoints:
      - {}